# http://travis-ci.org/#!/jupyter/jupyterhub
language: python
sudo: false
python:
    - 3.7
    - 3.6
    - 3.5
env:
    - JHUB_VER=0.9.6
    - JHUB_VER=1.0.0
matrix:
    include:
     - python: 3.7
       env: JHUB_VER=master
    allow_failures:
      - env: JHUB_VER=master

before_install:
    - npm install -g configurable-http-proxy
    - git clone --quiet --branch $JHUB_VER https://github.com/jupyter/jupyterhub.git jupyterhub
    - pip install --upgrade pip
install:
    - pip install --pre -r jupyterhub/dev-requirements.txt
    - pip install --pre -e jupyterhub
    - pip install --pre -f travis-wheels/wheelhouse -r requirements.txt

script:
    - travis_retry py.test --lf --cov batchspawner batchspawner/tests -v
